<a href="https://colab.research.google.com/github/HowardChen0211/dataManPy/blob/main/ProblemSet_0_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

## U.S. Housing Market Trends

### Research Question

How have home values, rental prices, and housing inventory changed across major U.S. metropolitan areas, and what is the relationship between changes in home values and rental prices?

### Objectives

1. Clean and standardize Zillow housing datasets.
2. Transform monthly housing data into an analysis-ready format.
3. Integrate home value, rental, and inventory datasets.
4. Analyze housing trends across metropolitan areas.
5. Examine the relationship between home value and rent growth.

# ProblemSet 0

## Import Libraries

In [ ]:
import numpy as np
import pandas as pd

#will display all output not just last command
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Load the data
https://www.zillow.com/research/data/

In [ ]:
# Zillow Home Value Index (ZHVI)
!wget -q -O ZHVI.csv https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv?t=1788564553
# Zillow Observed Rent Index (ZORI)
!wget -q -O ZORI.csv https://files.zillowstatic.com/research/public_csvs/zori/Metro_zori_uc_sfrcondomfr_sm_month.csv?t=1788564553
# For-Sale Inventory
!wget -q -O inventory.csv https://files.zillowstatic.com/research/public_csvs/invt_fs/Metro_invt_fs_uc_sfrcondo_sm_month.csv?t=1788564553

In [ ]:
!ls

inventory.csv  sample_data  ZHVI.csv  ZORI.csv

In [ ]:
# Read the data
zhvi = pd.read_csv("ZHVI.csv")
zori = pd.read_csv("ZORI.csv")
inve = pd.read_csv("inventory.csv")

In [ ]:
# See how many features in the data
print("Home Index: ", zhvi.columns)
print("Rent Index: ", zori.columns)
print("House inventory: ", inve.columns)

Home Index:  Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31',
       ...
       '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28',
       '2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31'],
      dtype='object', length=324)
Rent Index:  Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30', '2015-05-31',
       ...
       '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28',
       '2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31'],
      dtype='object', length=144)
House inventory:  Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2018-03-31', '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31',
       ...
       '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28',
       '2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31'],
      dtype='object', length=106)

In [ ]:
# take a look about the data (first 5 rows)
print(zhvi.head())

   RegionID  SizeRank       RegionName RegionType StateName     2000-01-31  \
0    102001         0    United States    country       NaN  124760.353386
1    394913         1     New York, NY        msa        NY  221730.961420
2    753899         2  Los Angeles, CA        msa        CA  225112.633581
3    394463         3      Chicago, IL        msa        IL  158537.235557
4    394514         4       Dallas, TX        msa        TX  131282.417502

      2000-02-29     2000-03-31     2000-04-30     2000-05-31  ...  \
0  124979.846843  125252.051048  125835.875637  126507.787743  ...
1  222673.192902  223624.151144  225551.160519  227546.645459  ...
2  225950.338198  227066.152759  229286.248907  231714.338088  ...
3  158683.994854  158963.500519  159658.841153  160495.252299  ...
4  131340.891150  131408.112593  131582.679622  131812.841469  ...

      2025-10-31     2025-11-30     2025-12-31     2026-01-31     2026-02-28  \
0  368600.830990  369290.109714  370096.503345  370865.855786  371594.025445
1  711084.998310  714481.548049  717957.123329  721070.448456  724701.411953
2  958467.862334  961838.271934  965861.431836  968431.823262  969683.356261
3  347939.585960  349538.582140  351328.450802  353002.256461  354806.848210
4  372246.711434  371975.510588  371751.570814  371305.648235  370713.999305

      2026-03-31     2026-04-30     2026-05-31     2026-06-30     2026-07-31
0  372094.225425  372175.152586  371910.603335  371664.627433  371774.013984
1  728550.827603  730998.279366  732547.901292  734053.602437  737078.239973
2  969344.133347  967696.188085  966216.924715  964714.939801  964933.539367
3  356259.214604  357291.377201  357923.452730  358804.309842  360261.570973
4  369629.029256  368279.710153  366682.370547  365420.503097  364792.581562

[5 rows x 324 columns]

In [ ]:
# take a look about the data (first 5 rows)
print(zori.head())

   RegionID  SizeRank       RegionName RegionType StateName   2015-01-31  \
0    102001         0    United States    country       NaN  1150.458020
1    394913         1     New York, NY        msa        NY  2283.102284
2    753899         2  Los Angeles, CA        msa        CA  1754.647191
3    394463         3      Chicago, IL        msa        IL  1380.831174
4    394514         4       Dallas, TX        msa        TX  1056.351903

    2015-02-28   2015-03-31   2015-04-30   2015-05-31  ...   2025-10-31  \
0  1156.813729  1165.483604  1174.328410  1183.035007  ...  1917.015885
1  2298.430193  2318.004173  2337.299847  2352.535819  ...  3480.248872
2  1765.832563  1781.036708  1796.290752  1811.474759  ...  2905.510423
3  1388.440562  1398.710597  1408.491034  1418.255705  ...  2141.436367
4  1061.180439  1068.880404  1080.006784  1089.134956  ...  1653.561913

    2025-11-30   2025-12-31   2026-01-31   2026-02-28   2026-03-31  \
0  1913.158141  1909.613807  1911.099804  1918.090366  1928.717336
1  3459.329392  3447.633327  3445.764531  3464.250818  3494.974421
2  2900.366545  2892.220790  2894.669544  2901.080983  2914.634187
3  2138.222886  2136.829818  2148.041168  2166.006337  2188.262661
4  1648.184400  1643.125933  1640.774793  1643.861562  1650.722236

    2026-04-30   2026-05-31   2026-06-30   2026-07-31
0  1939.279576  1948.758837  1956.535779  1962.188014
1  3527.038595  3565.477382  3597.970728  3627.457796
2  2924.958510  2934.850614  2941.837391  2944.420416
3  2208.104728  2227.663791  2244.133827  2252.637940
4  1659.693619  1664.270817  1667.030802  1667.042802

[5 rows x 144 columns]

In [ ]:
# take a look about the data (first 5 rows)
print(inve.head())

   RegionID  SizeRank       RegionName RegionType StateName  2018-03-31  \
0    102001         0    United States    country       NaN   1421529.0
1    394913         1     New York, NY        msa        NY     73707.0
2    753899         2  Los Angeles, CA        msa        CA     21998.0
3    394463         3      Chicago, IL        msa        IL     38581.0
4    394514         4       Dallas, TX        msa        TX     24042.0

   2018-04-30  2018-05-31  2018-06-30  2018-07-31  ...  2025-10-31  \
0   1500195.0   1592417.0   1660618.0   1709146.0  ...   1362843.0
1     80345.0     85864.0     90067.0     91881.0  ...     46780.0
2     23784.0     25605.0     27109.0     28811.0  ...     25800.0
3     42253.0     45757.0     47492.0     48984.0  ...     23989.0
4     25876.0     28224.0     30490.0     32408.0  ...     37328.0

   2025-11-30  2025-12-31  2026-01-31  2026-02-28  2026-03-31  2026-04-30  \
0   1322714.0   1239487.0   1158753.0   1115629.0   1155751.0   1219194.0
1     45625.0     41934.0     38091.0     35727.0     37165.0     40652.0
2     24235.0     21849.0     20064.0     19707.0     21155.0     22774.0
3     22985.0     20628.0     18354.0     17282.0     18268.0     19753.0
4     35783.0     33498.0     31315.0     30189.0     31276.0     32753.0

   2026-05-31  2026-06-30  2026-07-31
0   1300705.0   1355524.0   1389936.0
1     45324.0     48690.0     49835.0
2     24372.0     25314.0     25970.0
3     21673.0     23157.0     24116.0
4     34593.0     35802.0     36826.0

[5 rows x 106 columns]

In [ ]:
# See how big the data
print(zhvi.shape) # (895, 324)
print(zori.shape) # (752, 144)
print(inve.shape) # (928, 106)

(895, 324)
(752, 144)
(928, 106)

In [ ]:
# Descriptive Statistics
print(zhvi.describe())

            RegionID    SizeRank     2000-01-31     2000-02-29     2000-03-31  \
count     895.000000  895.000000     431.000000     432.000000     433.000000
mean   412099.672626  461.751955  112007.168265  112189.679727  112349.784272
std     78377.355083  268.710532   47147.278564   47261.860511   47454.538063
min    102001.000000    0.000000   47163.616003   47296.457254   47506.926839
25%    394546.000000  230.500000   81175.537933   81341.074578   81444.482625
50%    394795.000000  460.000000  100268.959265  100567.262007  100560.353029
75%    395044.500000  689.500000  129400.961787  129416.487044  129470.506019
max    753929.000000  939.000000  365836.645069  367722.135284  370562.591802

          2000-04-30     2000-05-31     2000-06-30     2000-07-31  \
count     435.000000     437.000000     438.000000     439.000000
mean   113044.556931  113790.485103  114362.467063  115158.441100
std     48122.245697   48720.401481   49350.022714   50084.307350
min     47812.846039   48120.648497   48231.794633   48194.737088
25%     81743.010370   82230.904942   82718.529732   83056.433102
50%    101201.553815  101685.984867  101924.778996  102610.484111
75%    129966.429575  130499.161002  131235.392709  131936.287711
max    378254.752063  386319.510820  395559.782054  403514.820889

          2000-08-31  ...    2025-10-31    2025-11-30    2025-12-31  \
count     440.000000  ...  8.950000e+02  8.950000e+02  8.950000e+02
mean   115792.879568  ...  2.961676e+05  2.969374e+05  2.979343e+05
std     50831.470879  ...  1.756725e+05  1.763819e+05  1.770171e+05
min     48145.252450  ...  4.899667e+04  4.867172e+04  4.819922e+04
25%     83286.954918  ...  1.889582e+05  1.895882e+05  1.902396e+05
50%    102680.266658  ...  2.496082e+05  2.505224e+05  2.519069e+05
75%    132124.261961  ...  3.484529e+05  3.502908e+05  3.512162e+05
max    413306.603538  ...  1.575183e+06  1.590350e+06  1.604452e+06

         2026-01-31    2026-02-28    2026-03-31    2026-04-30    2026-05-31  \
count  8.950000e+02  8.950000e+02  8.950000e+02  8.950000e+02  8.950000e+02
mean   2.990020e+05  3.000852e+05  3.009491e+05  3.013125e+05  3.012884e+05
std    1.774370e+05  1.776294e+05  1.776689e+05  1.773301e+05  1.770226e+05
min    4.773233e+04  4.779784e+04  4.840270e+04  4.875624e+04  4.895036e+04
25%    1.910684e+05  1.927913e+05  1.938140e+05  1.940414e+05  1.940063e+05
50%    2.529400e+05  2.541899e+05  2.551161e+05  2.550891e+05  2.555143e+05
75%    3.519468e+05  3.536805e+05  3.548529e+05  3.546412e+05  3.548829e+05
max    1.609578e+06  1.605998e+06  1.596239e+06  1.583147e+06  1.571055e+06

         2026-06-30    2026-07-31
count  8.950000e+02  8.950000e+02
mean   3.012498e+05  3.014634e+05
std    1.768151e+05  1.771194e+05
min    4.864572e+04  4.841446e+04
25%    1.940068e+05  1.942291e+05
50%    2.556724e+05  2.554725e+05
75%    3.552531e+05  3.558341e+05
max    1.561131e+06  1.559187e+06

[8 rows x 321 columns]

In [ ]:
# prints information about a DataFrame
print(zhvi.info())
print(zori.info())
print(inve.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895 entries, 0 to 894
Columns: 324 entries, RegionID to 2026-07-31
dtypes: float64(319), int64(2), object(3)
memory usage: 2.2+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 752 entries, 0 to 751
Columns: 144 entries, RegionID to 2026-07-31
dtypes: float64(139), int64(2), object(3)
memory usage: 846.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 928 entries, 0 to 927
Columns: 106 entries, RegionID to 2026-07-31
dtypes: float64(101), int64(2), object(3)
memory usage: 768.6+ KB
None

In [ ]:
# Missing values
print(zhvi.isna().sum())
print(zori.isna().sum())
print(inve.isna().sum())

RegionID      0
SizeRank      0
RegionName    0
RegionType    0
StateName     1
             ..
2026-03-31    0
2026-04-30    0
2026-05-31    0
2026-06-30    0
2026-07-31    0
Length: 324, dtype: int64
RegionID       0
SizeRank       0
RegionName     0
RegionType     0
StateName      1
              ..
2026-03-31    87
2026-04-30    76
2026-05-31    59
2026-06-30    48
2026-07-31     2
Length: 144, dtype: int64
RegionID      0
SizeRank      0
RegionName    0
RegionType    0
StateName     1
             ..
2026-03-31    0
2026-04-30    0
2026-05-31    0
2026-06-30    0
2026-07-31    0
Length: 106, dtype: int64

In [ ]:
# Check Duplicates
print(zhvi.duplicated().sum())
print(zori.duplicated().sum())
print(inve.duplicated().sum())

0
0
0

#### Make sure the data match across all three datasets, so I filtered the dates to include only records from 2019 to 2026.

In [ ]:
# ZHVI
columns = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

filter_2019 = columns + [i for i in zhvi.columns if i[0].isdigit() and i >= "2019-01"]

zhvi_2019 = zhvi[filter_2019]

zhvi_2019

,RegionID,SizeRank,RegionName,RegionType,StateName,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,...,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31
0,102001,0,United States,country,NaN,241014.471564,242182.064506,243415.837440,244516.238805,245336.619710,...,368600.830990,369290.109714,370096.503345,370865.855786,371594.025445,372094.225425,372175.152586,371910.603335,371664.627433,371774.013984
1,394913,1,"New York, NY",msa,NY,498287.591621,499885.462809,501925.475503,504147.580913,505622.589319,...,711084.998310,714481.548049,717957.123329,721070.448456,724701.411953,728550.827603,730998.279366,732547.901292,734053.602437,737078.239973
2,753899,2,"Los Angeles, CA",msa,CA,669742.116243,663327.517294,655514.696816,650534.661418,647998.378699,...,958467.862334,961838.271934,965861.431836,968431.823262,969683.356261,969344.133347,967696.188085,966216.924715,964714.939801,964933.539367
3,394463,3,"Chicago, IL",msa,IL,242261.043693,243510.160898,244689.408200,245633.431903,246062.330341,...,347939.585960,349538.582140,351328.450802,353002.256461,354806.848210,356259.214604,357291.377201,357923.452730,358804.309842,360261.570973
4,394514,4,"Dallas, TX",msa,TX,259008.588314,260035.252570,260918.262889,261403.710698,261603.166180,...,372246.711434,371975.510588,371751.570814,371305.648235,370713.999305,369629.029256,368279.710153,366682.370547,365420.503097,364792.581562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,753929,935,"Zapata, TX",msa,TX,139003.154212,139815.973622,140916.037687,143219.211286,145611.110958,...,129027.989391,128202.593056,128161.505083,128950.578363,129785.121175,130851.240747,130425.242995,129041.050283,126668.839563,124767.500237
891,394743,936,"Ketchikan, AK",msa,AK,289972.859861,292683.916741,295674.440393,298083.308771,299511.591377,...,392899.303264,395349.341976,397442.405528,398691.943327,399419.464892,400968.099657,403072.432375,405707.087777,407920.022397,409071.991090
892,753874,937,"Craig, CO",msa,CO,178074.827743,178667.358372,179366.286225,180519.546135,181799.867422,...,306735.956576,306283.867417,305773.744106,305924.848202,306636.964827,307551.497769,308213.937316,309157.446007,309416.894735,308910.952629
893,395188,938,"Vernon, TX",msa,TX,94148.981245,95032.080178,95620.869814,95997.031120,96522.861428,...,100643.808258,101161.284998,102145.218989,102401.149862,102696.313317,102782.841785,103259.489020,103352.308307,103769.439704,104079.427907
894,394767,939,"Lamesa, TX",msa,TX,100549.285182,101590.881654,103276.845457,105134.787645,107258.896258,...,108772.059648,110128.039981,112505.915501,115234.187657,117564.918016,118086.634844,117439.733701,115906.276807,114952.555773,114459.816037

In [ ]:
# ZORI
columns = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

filter_2019 = columns + [i for i in zori.columns if i[0].isdigit() and i >= "2019-01"]

zori_2019 = zori[filter_2019]

zori_2019

,RegionID,SizeRank,RegionName,RegionType,StateName,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,...,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31
0,102001,0,United States,country,NaN,1356.850410,1362.711533,1372.830087,1382.893581,1392.651646,...,1917.015885,1913.158141,1909.613807,1911.099804,1918.090366,1928.717336,1939.279576,1948.758837,1956.535779,1962.188014
1,394913,1,"New York, NY",msa,NY,2514.831054,2524.607903,2541.202753,2559.678135,2580.142857,...,3480.248872,3459.329392,3447.633327,3445.764531,3464.250818,3494.974421,3527.038595,3565.477382,3597.970728,3627.457796
2,753899,2,"Los Angeles, CA",msa,CA,2191.210397,2195.048035,2206.367597,2217.399379,2230.199327,...,2905.510423,2900.366545,2892.220790,2894.669544,2901.080983,2914.634187,2924.958510,2934.850614,2941.837391,2944.420416
3,394463,3,"Chicago, IL",msa,IL,1531.677804,1542.097942,1558.040921,1571.735421,1583.999403,...,2141.436367,2138.222886,2136.829818,2148.041168,2166.006337,2188.262661,2208.104728,2227.663791,2244.133827,2252.637940
4,394514,4,"Dallas, TX",msa,TX,1262.972710,1266.876766,1277.092759,1285.808654,1294.550358,...,1653.561913,1648.184400,1643.125933,1640.774793,1643.861562,1650.722236,1659.693619,1664.270817,1667.030802,1667.042802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,394979,900,"Pierre, SD",msa,SD,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1285.426845,1406.927223,1422.212366,1430.469347,1398.500000
748,394498,905,"Cordele, GA",msa,GA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,925.000000
749,394996,915,"Portales, NM",msa,NM,NaN,NaN,NaN,NaN,NaN,...,948.172647,941.245581,956.459011,949.721908,964.658956,959.264422,969.251997,976.570813,972.944617,975.238095
750,394805,916,"Los Alamos, NM",msa,NM,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2482.502722,2554.579069,2603.493288,2649.450568,2749.166667
751,395186,932,"Vermillion, SD",msa,SD,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,812.500000

In [ ]:
# inventory
columns = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

filter_2019 = columns + [i for i in inve.columns if i[0].isdigit() and i >= "2019-01"]

inve_2019 = inve[filter_2019]

inve_2019

,RegionID,SizeRank,RegionName,RegionType,StateName,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,...,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31
0,102001,0,United States,country,NaN,1452604.0,1405516.0,1449966.0,1515571.0,1604228.0,...,1362843.0,1322714.0,1239487.0,1158753.0,1115629.0,1155751.0,1219194.0,1300705.0,1355524.0,1389936.0
1,394913,1,"New York, NY",msa,NY,76678.0,74497.0,78192.0,84211.0,91255.0,...,46780.0,45625.0,41934.0,38091.0,35727.0,37165.0,40652.0,45324.0,48690.0,49835.0
2,753899,2,"Los Angeles, CA",msa,CA,26635.0,25849.0,27132.0,28454.0,30124.0,...,25800.0,24235.0,21849.0,20064.0,19707.0,21155.0,22774.0,24372.0,25314.0,25970.0
3,394463,3,"Chicago, IL",msa,IL,38250.0,36754.0,39387.0,43789.0,48113.0,...,23989.0,22985.0,20628.0,18354.0,17282.0,18268.0,19753.0,21673.0,23157.0,24116.0
4,394514,4,"Dallas, TX",msa,TX,27727.0,27057.0,28543.0,30513.0,32932.0,...,37328.0,35783.0,33498.0,31315.0,30189.0,31276.0,32753.0,34593.0,35802.0,36826.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,753929,935,"Zapata, TX",msa,TX,48.0,47.0,47.0,47.0,49.0,...,42.0,43.0,45.0,49.0,49.0,49.0,44.0,42.0,41.0,40.0
924,394743,936,"Ketchikan, AK",msa,AK,85.0,81.0,80.0,81.0,86.0,...,65.0,60.0,54.0,48.0,45.0,46.0,52.0,59.0,65.0,68.0
925,753874,937,"Craig, CO",msa,CO,113.0,105.0,104.0,115.0,130.0,...,88.0,82.0,69.0,59.0,55.0,56.0,61.0,70.0,81.0,91.0
926,395188,938,"Vernon, TX",msa,TX,45.0,46.0,47.0,47.0,43.0,...,63.0,57.0,52.0,49.0,49.0,48.0,44.0,38.0,32.0,31.0
927,394767,939,"Lamesa, TX",msa,TX,24.0,28.0,34.0,40.0,41.0,...,33.0,35.0,35.0,34.0,33.0,34.0,33.0,34.0,31.0,34.0

#### Write a function for above code, so that only need to call once.

In [ ]:
# I'm trying to write above code into a function, which makes it clean.

def cleaning_data(data, start = "2019-01"):

  columns = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

  filter_2019 = columns + [i for i in data.columns if i[0].isdigit() and i >= start]

  return data[filter_2019]

zhvi_19, zori_19, inve_19 = (cleaning_data(d) for d in (zhvi, zori, inve))

# ProblemSet 1