<a href="https://colab.research.google.com/github/HowardChen0211/dataManPy/blob/main/ProblemSet_1_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

## U.S. Housing Market Trends

### Research Question

- How have home values, rental prices, and housing inventory changed across major U.S. metropolitan areas, and to what extent is home-value growth associated with rent growth?

- Which cities have seen the fastest rising housing prices?

- Correlation between home price increases and rent increases?


### Unit of Analysis

One observation = one U.S. metropolitan area in one month.



### Objectives

1. Clean and standardize Zillow housing datasets.
2. Transform monthly housing data into an analysis-ready format.
3. Integrate home value, rental, and inventory datasets.
4. Analyze housing trends across metropolitan areas.
5. Examine the relationship between home value and rent growth.

# ProblemSet 0

## Import Libraries

In [2]:
import numpy as np
import pandas as pd

#will display all output not just last command
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Load the data

In [3]:
# Zillow Home Value Index (ZHVI)
!wget -q -O ZHVI.csv https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv?t=1788564553
# Zillow Observed Rent Index (ZORI)
!wget -q -O ZORI.csv https://files.zillowstatic.com/research/public_csvs/zori/Metro_zori_uc_sfrcondomfr_sm_month.csv?t=1788564553
# For-Sale Inventory
!wget -q -O inventory.csv https://files.zillowstatic.com/research/public_csvs/invt_fs/Metro_invt_fs_uc_sfrcondo_sm_month.csv?t=1788564553

In [4]:
!ls

inventory.csv  sample_data  ZHVI.csv  ZORI.csv

In [5]:
# Read the data
zhvi = pd.read_csv("ZHVI.csv")
zori = pd.read_csv("ZORI.csv")
inve = pd.read_csv("inventory.csv")

In [6]:
# See how many features in the data
print("Home Index: ", zhvi.columns)
print("Rent Index: ", zori.columns)
print("House inventory: ", inve.columns)

Home Index:  Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31',
       ...
       '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28',
       '2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31'],
      dtype='object', length=324)
Rent Index:  Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30', '2015-05-31',
       ...
       '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28',
       '2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31'],
      dtype='object', length=144)
House inventory:  Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2018-03-31', '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31',
       ...
       '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28',
       '2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31'],
      dtype='object', length=106)

In [7]:
# take a look about the data (first 5 rows)
print(zhvi.head())

   RegionID  SizeRank       RegionName RegionType StateName     2000-01-31  \
0    102001         0    United States    country       NaN  124760.353386
1    394913         1     New York, NY        msa        NY  221730.961420
2    753899         2  Los Angeles, CA        msa        CA  225112.633581
3    394463         3      Chicago, IL        msa        IL  158537.235557
4    394514         4       Dallas, TX        msa        TX  131282.417502

      2000-02-29     2000-03-31     2000-04-30     2000-05-31  ...  \
0  124979.846843  125252.051048  125835.875637  126507.787743  ...
1  222673.192902  223624.151144  225551.160519  227546.645459  ...
2  225950.338198  227066.152759  229286.248907  231714.338088  ...
3  158683.994854  158963.500519  159658.841153  160495.252299  ...
4  131340.891150  131408.112593  131582.679622  131812.841469  ...

      2025-10-31     2025-11-30     2025-12-31     2026-01-31     2026-02-28  \
0  368600.830990  369290.109714  370096.503345  370865.855786  371594.025445
1  711084.998310  714481.548049  717957.123329  721070.448456  724701.411953
2  958467.862334  961838.271934  965861.431836  968431.823262  969683.356261
3  347939.585960  349538.582140  351328.450802  353002.256461  354806.848210
4  372246.711434  371975.510588  371751.570814  371305.648235  370713.999305

      2026-03-31     2026-04-30     2026-05-31     2026-06-30     2026-07-31
0  372094.225425  372175.152586  371910.603335  371664.627433  371774.013984
1  728550.827603  730998.279366  732547.901292  734053.602437  737078.239973
2  969344.133347  967696.188085  966216.924715  964714.939801  964933.539367
3  356259.214604  357291.377201  357923.452730  358804.309842  360261.570973
4  369629.029256  368279.710153  366682.370547  365420.503097  364792.581562

[5 rows x 324 columns]

In [8]:
# take a look about the data (first 5 rows)
print(zori.head())

   RegionID  SizeRank       RegionName RegionType StateName   2015-01-31  \
0    102001         0    United States    country       NaN  1150.458020
1    394913         1     New York, NY        msa        NY  2283.102284
2    753899         2  Los Angeles, CA        msa        CA  1754.647191
3    394463         3      Chicago, IL        msa        IL  1380.831174
4    394514         4       Dallas, TX        msa        TX  1056.351903

    2015-02-28   2015-03-31   2015-04-30   2015-05-31  ...   2025-10-31  \
0  1156.813729  1165.483604  1174.328410  1183.035007  ...  1917.015885
1  2298.430193  2318.004173  2337.299847  2352.535819  ...  3480.248872
2  1765.832563  1781.036708  1796.290752  1811.474759  ...  2905.510423
3  1388.440562  1398.710597  1408.491034  1418.255705  ...  2141.436367
4  1061.180439  1068.880404  1080.006784  1089.134956  ...  1653.561913

    2025-11-30   2025-12-31   2026-01-31   2026-02-28   2026-03-31  \
0  1913.158141  1909.613807  1911.099804  1918.090366  1928.717336
1  3459.329392  3447.633327  3445.764531  3464.250818  3494.974421
2  2900.366545  2892.220790  2894.669544  2901.080983  2914.634187
3  2138.222886  2136.829818  2148.041168  2166.006337  2188.262661
4  1648.184400  1643.125933  1640.774793  1643.861562  1650.722236

    2026-04-30   2026-05-31   2026-06-30   2026-07-31
0  1939.279576  1948.758837  1956.535779  1962.188014
1  3527.038595  3565.477382  3597.970728  3627.457796
2  2924.958510  2934.850614  2941.837391  2944.420416
3  2208.104728  2227.663791  2244.133827  2252.637940
4  1659.693619  1664.270817  1667.030802  1667.042802

[5 rows x 144 columns]

In [9]:
# take a look about the data (first 5 rows)
print(inve.head())

   RegionID  SizeRank       RegionName RegionType StateName  2018-03-31  \
0    102001         0    United States    country       NaN   1421529.0
1    394913         1     New York, NY        msa        NY     73707.0
2    753899         2  Los Angeles, CA        msa        CA     21998.0
3    394463         3      Chicago, IL        msa        IL     38581.0
4    394514         4       Dallas, TX        msa        TX     24042.0

   2018-04-30  2018-05-31  2018-06-30  2018-07-31  ...  2025-10-31  \
0   1500195.0   1592417.0   1660618.0   1709146.0  ...   1362843.0
1     80345.0     85864.0     90067.0     91881.0  ...     46780.0
2     23784.0     25605.0     27109.0     28811.0  ...     25800.0
3     42253.0     45757.0     47492.0     48984.0  ...     23989.0
4     25876.0     28224.0     30490.0     32408.0  ...     37328.0

   2025-11-30  2025-12-31  2026-01-31  2026-02-28  2026-03-31  2026-04-30  \
0   1322714.0   1239487.0   1158753.0   1115629.0   1155751.0   1219194.0
1     45625.0     41934.0     38091.0     35727.0     37165.0     40652.0
2     24235.0     21849.0     20064.0     19707.0     21155.0     22774.0
3     22985.0     20628.0     18354.0     17282.0     18268.0     19753.0
4     35783.0     33498.0     31315.0     30189.0     31276.0     32753.0

   2026-05-31  2026-06-30  2026-07-31
0   1300705.0   1355524.0   1389936.0
1     45324.0     48690.0     49835.0
2     24372.0     25314.0     25970.0
3     21673.0     23157.0     24116.0
4     34593.0     35802.0     36826.0

[5 rows x 106 columns]

In [10]:
# See how big the data
print(zhvi.shape) # (895, 324)
print(zori.shape) # (752, 144)
print(inve.shape) # (928, 106)

(895, 324)
(752, 144)
(928, 106)

In [11]:
# Descriptive Statistics
print(zhvi.describe())

            RegionID    SizeRank     2000-01-31     2000-02-29     2000-03-31  \
count     895.000000  895.000000     431.000000     432.000000     433.000000
mean   412099.672626  461.751955  112007.168265  112189.679727  112349.784272
std     78377.355083  268.710532   47147.278564   47261.860511   47454.538063
min    102001.000000    0.000000   47163.616003   47296.457254   47506.926839
25%    394546.000000  230.500000   81175.537933   81341.074578   81444.482625
50%    394795.000000  460.000000  100268.959265  100567.262007  100560.353029
75%    395044.500000  689.500000  129400.961787  129416.487044  129470.506019
max    753929.000000  939.000000  365836.645069  367722.135284  370562.591802

          2000-04-30     2000-05-31     2000-06-30     2000-07-31  \
count     435.000000     437.000000     438.000000     439.000000
mean   113044.556931  113790.485103  114362.467063  115158.441100
std     48122.245697   48720.401481   49350.022714   50084.307350
min     47812.846039   48120.648497   48231.794633   48194.737088
25%     81743.010370   82230.904942   82718.529732   83056.433102
50%    101201.553815  101685.984867  101924.778996  102610.484111
75%    129966.429575  130499.161002  131235.392709  131936.287711
max    378254.752063  386319.510820  395559.782054  403514.820889

          2000-08-31  ...    2025-10-31    2025-11-30    2025-12-31  \
count     440.000000  ...  8.950000e+02  8.950000e+02  8.950000e+02
mean   115792.879568  ...  2.961676e+05  2.969374e+05  2.979343e+05
std     50831.470879  ...  1.756725e+05  1.763819e+05  1.770171e+05
min     48145.252450  ...  4.899667e+04  4.867172e+04  4.819922e+04
25%     83286.954918  ...  1.889582e+05  1.895882e+05  1.902396e+05
50%    102680.266658  ...  2.496082e+05  2.505224e+05  2.519069e+05
75%    132124.261961  ...  3.484529e+05  3.502908e+05  3.512162e+05
max    413306.603538  ...  1.575183e+06  1.590350e+06  1.604452e+06

         2026-01-31    2026-02-28    2026-03-31    2026-04-30    2026-05-31  \
count  8.950000e+02  8.950000e+02  8.950000e+02  8.950000e+02  8.950000e+02
mean   2.990020e+05  3.000852e+05  3.009491e+05  3.013125e+05  3.012884e+05
std    1.774370e+05  1.776294e+05  1.776689e+05  1.773301e+05  1.770226e+05
min    4.773233e+04  4.779784e+04  4.840270e+04  4.875624e+04  4.895036e+04
25%    1.910684e+05  1.927913e+05  1.938140e+05  1.940414e+05  1.940063e+05
50%    2.529400e+05  2.541899e+05  2.551161e+05  2.550891e+05  2.555143e+05
75%    3.519468e+05  3.536805e+05  3.548529e+05  3.546412e+05  3.548829e+05
max    1.609578e+06  1.605998e+06  1.596239e+06  1.583147e+06  1.571055e+06

         2026-06-30    2026-07-31
count  8.950000e+02  8.950000e+02
mean   3.012498e+05  3.014634e+05
std    1.768151e+05  1.771194e+05
min    4.864572e+04  4.841446e+04
25%    1.940068e+05  1.942291e+05
50%    2.556724e+05  2.554725e+05
75%    3.552531e+05  3.558341e+05
max    1.561131e+06  1.559187e+06

[8 rows x 321 columns]

In [12]:
# prints information about a DataFrame
print(zhvi.info())
print(zori.info())
print(inve.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895 entries, 0 to 894
Columns: 324 entries, RegionID to 2026-07-31
dtypes: float64(319), int64(2), object(3)
memory usage: 2.2+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 752 entries, 0 to 751
Columns: 144 entries, RegionID to 2026-07-31
dtypes: float64(139), int64(2), object(3)
memory usage: 846.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 928 entries, 0 to 927
Columns: 106 entries, RegionID to 2026-07-31
dtypes: float64(101), int64(2), object(3)
memory usage: 768.6+ KB
None

In [13]:
# Missing values
print(zhvi.isna().sum())
print(zori.isna().sum())
print(inve.isna().sum())

RegionID      0
SizeRank      0
RegionName    0
RegionType    0
StateName     1
             ..
2026-03-31    0
2026-04-30    0
2026-05-31    0
2026-06-30    0
2026-07-31    0
Length: 324, dtype: int64
RegionID       0
SizeRank       0
RegionName     0
RegionType     0
StateName      1
              ..
2026-03-31    87
2026-04-30    76
2026-05-31    59
2026-06-30    48
2026-07-31     2
Length: 144, dtype: int64
RegionID      0
SizeRank      0
RegionName    0
RegionType    0
StateName     1
             ..
2026-03-31    0
2026-04-30    0
2026-05-31    0
2026-06-30    0
2026-07-31    0
Length: 106, dtype: int64

In [14]:
# Check Duplicates
print(zhvi.duplicated().sum())
print(zori.duplicated().sum())
print(inve.duplicated().sum())

0
0
0

#### Make sure the data match across all three datasets, so I filtered the dates to include only records from 2019 to 2026.

In [15]:
# ZHVI
columns = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

filter_2019 = columns + [i for i in zhvi.columns if i[0].isdigit() and i >= "2019-01"]

zhvi_2019 = zhvi[filter_2019]

zhvi_2019

,RegionID,SizeRank,RegionName,RegionType,StateName,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,...,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31
0,102001,0,United States,country,NaN,241014.471564,242182.064506,243415.837440,244516.238805,245336.619710,...,368600.830990,369290.109714,370096.503345,370865.855786,371594.025445,372094.225425,372175.152586,371910.603335,371664.627433,371774.013984
1,394913,1,"New York, NY",msa,NY,498287.591621,499885.462809,501925.475503,504147.580913,505622.589319,...,711084.998310,714481.548049,717957.123329,721070.448456,724701.411953,728550.827603,730998.279366,732547.901292,734053.602437,737078.239973
2,753899,2,"Los Angeles, CA",msa,CA,669742.116243,663327.517294,655514.696816,650534.661418,647998.378699,...,958467.862334,961838.271934,965861.431836,968431.823262,969683.356261,969344.133347,967696.188085,966216.924715,964714.939801,964933.539367
3,394463,3,"Chicago, IL",msa,IL,242261.043693,243510.160898,244689.408200,245633.431903,246062.330341,...,347939.585960,349538.582140,351328.450802,353002.256461,354806.848210,356259.214604,357291.377201,357923.452730,358804.309842,360261.570973
4,394514,4,"Dallas, TX",msa,TX,259008.588314,260035.252570,260918.262889,261403.710698,261603.166180,...,372246.711434,371975.510588,371751.570814,371305.648235,370713.999305,369629.029256,368279.710153,366682.370547,365420.503097,364792.581562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,753929,935,"Zapata, TX",msa,TX,139003.154212,139815.973622,140916.037687,143219.211286,145611.110958,...,129027.989391,128202.593056,128161.505083,128950.578363,129785.121175,130851.240747,130425.242995,129041.050283,126668.839563,124767.500237
891,394743,936,"Ketchikan, AK",msa,AK,289972.859861,292683.916741,295674.440393,298083.308771,299511.591377,...,392899.303264,395349.341976,397442.405528,398691.943327,399419.464892,400968.099657,403072.432375,405707.087777,407920.022397,409071.991090
892,753874,937,"Craig, CO",msa,CO,178074.827743,178667.358372,179366.286225,180519.546135,181799.867422,...,306735.956576,306283.867417,305773.744106,305924.848202,306636.964827,307551.497769,308213.937316,309157.446007,309416.894735,308910.952629
893,395188,938,"Vernon, TX",msa,TX,94148.981245,95032.080178,95620.869814,95997.031120,96522.861428,...,100643.808258,101161.284998,102145.218989,102401.149862,102696.313317,102782.841785,103259.489020,103352.308307,103769.439704,104079.427907
894,394767,939,"Lamesa, TX",msa,TX,100549.285182,101590.881654,103276.845457,105134.787645,107258.896258,...,108772.059648,110128.039981,112505.915501,115234.187657,117564.918016,118086.634844,117439.733701,115906.276807,114952.555773,114459.816037

In [16]:
# ZORI
columns = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

filter_2019 = columns + [i for i in zori.columns if i[0].isdigit() and i >= "2019-01"]

zori_2019 = zori[filter_2019]

zori_2019

,RegionID,SizeRank,RegionName,RegionType,StateName,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,...,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31
0,102001,0,United States,country,NaN,1356.850410,1362.711533,1372.830087,1382.893581,1392.651646,...,1917.015885,1913.158141,1909.613807,1911.099804,1918.090366,1928.717336,1939.279576,1948.758837,1956.535779,1962.188014
1,394913,1,"New York, NY",msa,NY,2514.831054,2524.607903,2541.202753,2559.678135,2580.142857,...,3480.248872,3459.329392,3447.633327,3445.764531,3464.250818,3494.974421,3527.038595,3565.477382,3597.970728,3627.457796
2,753899,2,"Los Angeles, CA",msa,CA,2191.210397,2195.048035,2206.367597,2217.399379,2230.199327,...,2905.510423,2900.366545,2892.220790,2894.669544,2901.080983,2914.634187,2924.958510,2934.850614,2941.837391,2944.420416
3,394463,3,"Chicago, IL",msa,IL,1531.677804,1542.097942,1558.040921,1571.735421,1583.999403,...,2141.436367,2138.222886,2136.829818,2148.041168,2166.006337,2188.262661,2208.104728,2227.663791,2244.133827,2252.637940
4,394514,4,"Dallas, TX",msa,TX,1262.972710,1266.876766,1277.092759,1285.808654,1294.550358,...,1653.561913,1648.184400,1643.125933,1640.774793,1643.861562,1650.722236,1659.693619,1664.270817,1667.030802,1667.042802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,394979,900,"Pierre, SD",msa,SD,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1285.426845,1406.927223,1422.212366,1430.469347,1398.500000
748,394498,905,"Cordele, GA",msa,GA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,925.000000
749,394996,915,"Portales, NM",msa,NM,NaN,NaN,NaN,NaN,NaN,...,948.172647,941.245581,956.459011,949.721908,964.658956,959.264422,969.251997,976.570813,972.944617,975.238095
750,394805,916,"Los Alamos, NM",msa,NM,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2482.502722,2554.579069,2603.493288,2649.450568,2749.166667
751,395186,932,"Vermillion, SD",msa,SD,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,812.500000

In [17]:
# inventory
columns = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

filter_2019 = columns + [i for i in inve.columns if i[0].isdigit() and i >= "2019-01"]

inve_2019 = inve[filter_2019]

inve_2019

,RegionID,SizeRank,RegionName,RegionType,StateName,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,...,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31
0,102001,0,United States,country,NaN,1452604.0,1405516.0,1449966.0,1515571.0,1604228.0,...,1362843.0,1322714.0,1239487.0,1158753.0,1115629.0,1155751.0,1219194.0,1300705.0,1355524.0,1389936.0
1,394913,1,"New York, NY",msa,NY,76678.0,74497.0,78192.0,84211.0,91255.0,...,46780.0,45625.0,41934.0,38091.0,35727.0,37165.0,40652.0,45324.0,48690.0,49835.0
2,753899,2,"Los Angeles, CA",msa,CA,26635.0,25849.0,27132.0,28454.0,30124.0,...,25800.0,24235.0,21849.0,20064.0,19707.0,21155.0,22774.0,24372.0,25314.0,25970.0
3,394463,3,"Chicago, IL",msa,IL,38250.0,36754.0,39387.0,43789.0,48113.0,...,23989.0,22985.0,20628.0,18354.0,17282.0,18268.0,19753.0,21673.0,23157.0,24116.0
4,394514,4,"Dallas, TX",msa,TX,27727.0,27057.0,28543.0,30513.0,32932.0,...,37328.0,35783.0,33498.0,31315.0,30189.0,31276.0,32753.0,34593.0,35802.0,36826.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,753929,935,"Zapata, TX",msa,TX,48.0,47.0,47.0,47.0,49.0,...,42.0,43.0,45.0,49.0,49.0,49.0,44.0,42.0,41.0,40.0
924,394743,936,"Ketchikan, AK",msa,AK,85.0,81.0,80.0,81.0,86.0,...,65.0,60.0,54.0,48.0,45.0,46.0,52.0,59.0,65.0,68.0
925,753874,937,"Craig, CO",msa,CO,113.0,105.0,104.0,115.0,130.0,...,88.0,82.0,69.0,59.0,55.0,56.0,61.0,70.0,81.0,91.0
926,395188,938,"Vernon, TX",msa,TX,45.0,46.0,47.0,47.0,43.0,...,63.0,57.0,52.0,49.0,49.0,48.0,44.0,38.0,32.0,31.0
927,394767,939,"Lamesa, TX",msa,TX,24.0,28.0,34.0,40.0,41.0,...,33.0,35.0,35.0,34.0,33.0,34.0,33.0,34.0,31.0,34.0

#### Write a function for above code, so that only need to call once.

In [18]:
# I'm trying to write above code into a function, which makes it clean.

def cleaning_data(data, start = "2019-01"):

  columns = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

  filter_2019 = columns + [i for i in data.columns if i[0].isdigit() and i >= start]

  return data[filter_2019]

zhvi_19, zori_19, inve_19 = (cleaning_data(d) for d in (zhvi, zori, inve))

# ProblemSet 1

### Select Major Metropolitan Areas (Top 20)
Source: https://en.wikipedia.org/wiki/Metropolitan_statistical_area

In [27]:
# Location of the 20 largest MSAs in the United States, based on U.S. Census Bureau estimates for July 1, 2025

metros = [
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Dallas, TX",
    "Houston, TX",
    "Atlanta, GA",
    "Washington, DC",
    "Miami, FL",
    "Philadelphia, PA",
    "Phoenix, AZ",
    "Boston, MA",
    "Riverside, CA",
    "San Francisco, CA",
    "Detroit, MI",
    "Seattle, WA",
    "Minneapolis, MN",
    "Tampa, FL",
    "San Diego, CA",
    "Denver, CO",
    "Orlando, FL"
]

zhvi_19 = zhvi_19[zhvi_19["RegionName"].isin(metros)]

zori_19 = zori_19[zori_19["RegionName"].isin(metros)]

inve_19 = inve_19[inve_19["RegionName"].isin(metros)]

### ZHVI Data

In [28]:
# Make a copy so that don't alter the original data
zhvi = zhvi_19.copy()

In [29]:
# See the data types in the dataframe
zhvi.dtypes

RegionID        int64
SizeRank        int64
RegionName     object
RegionType     object
StateName      object
               ...
2026-03-31    float64
2026-04-30    float64
2026-05-31    float64
2026-06-30    float64
2026-07-31    float64
Length: 96, dtype: object

In [30]:
# Date columns shouldn't be float type, so I'll convert them to datetime format later.
zhvi.select_dtypes(include='float')

,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,...,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31
1,498287.591621,499885.462809,501925.475503,504147.580913,505622.589319,506922.467448,507631.811706,508131.095042,507857.256864,507892.742284,...,7.110850e+05,7.144815e+05,7.179571e+05,7.210704e+05,7.247014e+05,7.285508e+05,7.309983e+05,7.325479e+05,7.340536e+05,7.370782e+05
2,669742.116243,663327.517294,655514.696816,650534.661418,647998.378699,646714.073386,647554.032253,651388.743465,657691.981296,664439.714571,...,9.584679e+05,9.618383e+05,9.658614e+05,9.684318e+05,9.696834e+05,9.693441e+05,9.676962e+05,9.662169e+05,9.647149e+05,9.649335e+05
3,242261.043693,243510.160898,244689.408200,245633.431903,246062.330341,246277.876709,246090.024675,245865.877420,245395.412075,245280.600696,...,3.479396e+05,3.495386e+05,3.513285e+05,3.530023e+05,3.548068e+05,3.562592e+05,3.572914e+05,3.579235e+05,3.588043e+05,3.602616e+05
4,259008.588314,260035.252570,260918.262889,261403.710698,261603.166180,261665.240775,261764.219483,262012.760248,262405.485038,263116.859137,...,3.722467e+05,3.719755e+05,3.717516e+05,3.713056e+05,3.707140e+05,3.696290e+05,3.682797e+05,3.666824e+05,3.654205e+05,3.647926e+05
5,224326.559744,225199.813724,226030.698118,226649.908484,227115.600533,227437.149231,227764.457224,228141.881414,228624.828586,229278.552886,...,3.125691e+05,3.123751e+05,3.123942e+05,3.122638e+05,3.119370e+05,3.113693e+05,3.106458e+05,3.096337e+05,3.085406e+05,3.077720e+05
6,424472.478682,425862.880690,427791.823897,429895.805503,431263.803940,432021.333223,432415.254555,433026.521091,433651.118421,434660.495726,...,5.803990e+05,5.813793e+05,5.823323e+05,5.825214e+05,5.823386e+05,5.818379e+05,5.808180e+05,5.797472e+05,5.793739e+05,5.798115e+05
7,246026.836272,247174.152253,248414.649497,249451.087434,250124.844727,250791.600173,251427.490378,252069.361890,252565.880766,253234.572015,...,3.850269e+05,3.857030e+05,3.865939e+05,3.875311e+05,3.883976e+05,3.892899e+05,3.899628e+05,3.906458e+05,3.913533e+05,3.923294e+05
8,297321.119270,298498.943681,299171.941424,299544.400726,299397.527076,299323.787187,299477.627807,300012.194781,300725.458473,301819.518457,...,4.782793e+05,4.775568e+05,4.770886e+05,4.769341e+05,4.771802e+05,4.774794e+05,4.772762e+05,4.770436e+05,4.770090e+05,4.777692e+05
9,242626.432983,244173.451945,245478.540927,246510.090887,247317.348859,247924.008827,248528.907566,249224.378217,249948.567937,250886.506664,...,3.871095e+05,3.866621e+05,3.861360e+05,3.856044e+05,3.852316e+05,3.846354e+05,3.839151e+05,3.830045e+05,3.822774e+05,3.818720e+05
10,495148.397202,495414.078091,496400.169287,498094.275771,499370.919418,500472.564050,500938.601364,501088.781705,500948.663940,501616.835259,...,7.327684e+05,7.358585e+05,7.388786e+05,7.408849e+05,7.420096e+05,7.425757e+05,7.420013e+05,7.415344e+05,7.413537e+05,7.423410e+05
11,282119.609399,283718.464508,285213.379627,286411.485370,287270.548872,288178.911243,289037.059658,290194.866331,291671.658193,293521.283654,...,4.492279e+05,4.493577e+05,4.500087e+05,4.507342e+05,4.512755e+05,4.510534e+05,4.500317e+05,4.484400e+05,4.468442e+05,4.459238e+05
12,935107.607079,931178.180450,927826.784981,925499.603068,924059.397352,924103.466325,925177.329406,927562.092604,929402.517638,930755.756243,...,1.115663e+06,1.119505e+06,1.124747e+06,1.127784e+06,1.129945e+06,1.131093e+06,1.131591e+06,1.132560e+06,1.133393e+06,1.136810e+06
13,379469.984054,380134.462946,380553.271213,380850.235662,380484.297631,380058.013532,379958.650867,380542.245933,381892.010174,384000.285605,...,5.842247e+05,5.852971e+05,5.869330e+05,5.881226e+05,5.889193e+05,5.891924e+05,5.889671e+05,5.881700e+05,5.871885e+05,5.867978e+05
14,174546.568278,176189.936697,178064.093440,179615.230900,180848.962798,181781.349720,182293.275202,182411.171717,182199.661774,182233.405075,...,2.665995e+05,2.673291e+05,2.683056e+05,2.690709e+05,2.697979e+05,2.702522e+05,2.704400e+05,2.703123e+05,2.702108e+05,2.703699e+05
15,510597.551714,510295.215297,511415.206199,512911.438299,514049.796592,514642.232114,514806.178364,515006.886382,515093.654011,516260.860740,...,7.545396e+05,7.573952e+05,7.595408e+05,7.608139e+05,7.604608e+05,7.577005e+05,7.522755e+05,7.465227e+05,7.424104e+05,7.405794e+05
16,289392.727285,291306.293830,293308.913652,294997.372706,295926.583901,296530.851158,296892.521210,297217.641284,297400.076710,297932.337103,...,3.906291e+05,3.918517e+05,3.933279e+05,3.946119e+05,3.958234e+05,3.962242e+05,3.960004e+05,3.952268e+05,3.947334e+05,3.947113e+05
17,594883.113979,594666.437284,595636.329370,596978.332436,597729.758019,598242.134334,598250.104727,598986.233065,599436.672732,600583.609992,...,9.292523e+05,9.302635e+05,9.324467e+05,9.336823e+05,9.347070e+05,9.350873e+05,9.349707e+05,9.343898e+05,9.336960e+05,9.341656e+05
18,227539.689198,228675.041494,229501.687031,230244.882441,230795.540131,231564.280691,232378.311185,233388.968679,234225.226010,235207.906040,...,3.639935e+05,3.634215e+05,3.631376e+05,3.631899e+05,3.635499e+05,3.638600e+05,3.635523e+05,3.627215e+05,3.618791e+05,3.616338e+05
19,423967.910011,426319.242440,428837.781052,430924.546973,431768.553482,432164.421947,432318.179310,432971.563734,433714.175168,435055.485287,...,5.789362e+05,5.794799e+05,5.797125e+05,5.791875e+05,5.776090e+05,5.747482e+05,5.712288e+05,5.681682e+05,5.666197e+05,5.665285e+05
22,250909.289966,252722.288115,254289.472967,255416.662742,256145.481850,256865.772420,257628.613253,258370.871789,259094.520097,259969.267332,...,3.911239e+05,3.906690e+05,3.905795e+05,3.905992e+05,3.906034e+05,3.903074e+05,3.896270e+05,3.886178e+05,3.875190e+05,3.868670e+05

#### Reshape the Data
The data is often provided in a wide format, so I will unpivot it from wide to long format.

https://pandas.pydata.org/docs/reference/api/pandas.melt.html

In [31]:
id_col = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

date_col = []
for col in zhvi.columns:
  if col not in id_col:
    date_col.append(col)

zhvi = zhvi.melt(
    id_vars=id_col,
    value_vars=date_col,
    var_name="Date",
    value_name="ZHVI"
)

# Drop unused columns
zhvi = zhvi.drop(columns=["SizeRank", "RegionType"], axis=1)

#### Convert Dates

In [32]:
# Convert Dates to datetime type
zhvi["Date"] = pd.to_datetime(zhvi["Date"], errors = "coerce") # Turns invalid dates into NaT

# Check missing value in Date column
zhvi["Date"].isna().sum()

np.int64(0)

#### Sort the data

In [33]:
zhvi = zhvi.sort_values(
    by = ["RegionName", "Date"]).reset_index(drop=True)

zhvi.head()

   RegionID   RegionName StateName       Date           ZHVI
0    394347  Atlanta, GA        GA 2019-01-31  242626.432983
1    394347  Atlanta, GA        GA 2019-02-28  244173.451945
2    394347  Atlanta, GA        GA 2019-03-31  245478.540927
3    394347  Atlanta, GA        GA 2019-04-30  246510.090887
4    394347  Atlanta, GA        GA 2019-05-31  247317.348859

In [26]:
url = 'https://en.wikipedia.org/wiki/List_of_counties_in_California'

header = {
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

import requests
r = requests.get(url, headers=header)

pd.read_html(r.text,match='County',flavor=None)[0].head(3)

/tmp/ipykernel_778/1192926818.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(r.text,match='County',flavor=None)[0].head(3)

,County,FIPS code[8],County seat[9],Est.[9],Formed from,Etymology[10],General Law or Charter [6],Population (2025)[11],Area[9],Map
0,Alameda County,1,Oakland,1853,Contra Costa and Santa Clara,"The oak and other trees, once abundant in the ...",Charter,1636630,"738 sq mi (1,911 km2)",NaN
1,Alpine County,3,Markleeville,1864,"Amador, El Dorado, Calaveras, Mono and Tuolumne",Location high in the Sierra Nevada; alpine ref...,General Law,1043,"739 sq mi (1,914 km2)",NaN
2,Amador County,5,Jackson,1854,Calaveras,"Jose Maria Amador (1794–1883), a soldier, ranc...",General Law,41876,"593 sq mi (1,536 km2)",NaN

### ZORI Data

In [34]:
# Make a copy so that don't alter the original data
zori = zori_19.copy()

In [35]:
# See the data types in the dataframe
zori.dtypes

RegionID        int64
SizeRank        int64
RegionName     object
RegionType     object
StateName      object
               ...
2026-03-31    float64
2026-04-30    float64
2026-05-31    float64
2026-06-30    float64
2026-07-31    float64
Length: 96, dtype: object

In [36]:
# Date columns shouldn't be float type, so I'll convert them to datetime format later.
zori.select_dtypes(include='float')

,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,...,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31
1,2514.831054,2524.607903,2541.202753,2559.678135,2580.142857,2601.946088,2617.624874,2625.207312,2623.541400,2618.912459,...,3480.248872,3459.329392,3447.633327,3445.764531,3464.250818,3494.974421,3527.038595,3565.477382,3597.970728,3627.457796
2,2191.210397,2195.048035,2206.367597,2217.399379,2230.199327,2239.219552,2247.615349,2252.710445,2255.714627,2257.044774,...,2905.510423,2900.366545,2892.220790,2894.669544,2901.080983,2914.634187,2924.958510,2934.850614,2941.837391,2944.420416
3,1531.677804,1542.097942,1558.040921,1571.735421,1583.999403,1590.592780,1593.060425,1592.061924,1586.767949,1579.762442,...,2141.436367,2138.222886,2136.829818,2148.041168,2166.006337,2188.262661,2208.104728,2227.663791,2244.133827,2252.637940
4,1262.972710,1266.876766,1277.092759,1285.808654,1294.550358,1300.979788,1303.687839,1305.357073,1304.032840,1304.085868,...,1653.561913,1648.184400,1643.125933,1640.774793,1643.861562,1650.722236,1659.693619,1664.270817,1667.030802,1667.042802
5,1316.278256,1314.838145,1321.667239,1327.038243,1335.798062,1341.529948,1345.159590,1344.431780,1341.207018,1339.736719,...,1648.996314,1643.606086,1639.418321,1636.890826,1635.136294,1635.772154,1640.062950,1647.149486,1651.916470,1653.514326
6,1892.128834,1899.871366,1910.621863,1922.258932,1932.799972,1940.569442,1945.658673,1947.015299,1947.373415,1941.785886,...,2420.027229,2404.210744,2393.490806,2394.845729,2406.151808,2421.121589,2433.303297,2442.864577,2448.866805,2456.208770
7,1359.145173,1365.673272,1379.112691,1390.918242,1398.556391,1406.141716,1409.557656,1409.369185,1405.122642,1403.240682,...,1872.366581,1872.675034,1873.708085,1876.298910,1886.476817,1893.036296,1901.362036,1907.199485,1917.679143,1925.105582
8,1679.023143,1677.966869,1678.232983,1681.379820,1686.274179,1690.428835,1695.435850,1698.891299,1704.818627,1714.245191,...,2644.956197,2646.109496,2644.580914,2643.523846,2647.503629,2656.002215,2664.761543,2669.724140,2671.594976,2676.990987
9,1262.421129,1269.533329,1281.461408,1292.579433,1303.611816,1311.964670,1316.964275,1320.333888,1322.238293,1319.946800,...,1826.097059,1819.629447,1812.218460,1812.457466,1815.025742,1820.503498,1826.237193,1835.639730,1846.306541,1855.397132
10,2314.295549,2340.636092,2362.971286,2379.129533,2393.021048,2405.462606,2413.323464,2405.670554,2392.204477,2371.055398,...,3048.083418,3047.150206,3053.626949,3070.779840,3087.276895,3114.182155,3136.988361,3163.501411,3169.194946,3164.629260
11,1166.676965,1174.936812,1185.193937,1199.911316,1211.591462,1221.686347,1229.087932,1235.433500,1239.899574,1243.556663,...,1711.568552,1706.187040,1702.138026,1702.864969,1709.347871,1714.739970,1718.468963,1723.163640,1723.985573,1727.343387
12,2694.385105,2703.259057,2716.717997,2726.495572,2741.642532,2754.751643,2771.931878,2778.072514,2774.967128,2764.372189,...,3112.665742,3107.819710,3103.189773,3116.284879,3147.349051,3180.823698,3213.644723,3255.367172,3312.657548,3371.692026
13,1625.718603,1629.783331,1639.088840,1647.104442,1657.258575,1664.522127,1675.137822,1685.104077,1689.913190,1691.224777,...,2494.340514,2493.125479,2493.722196,2498.462154,2508.912757,2518.411753,2530.925743,2538.352440,2545.009998,2546.967547
14,1010.245296,1016.615951,1025.240239,1033.272335,1044.616649,1050.975739,1054.240954,1053.617881,1051.892901,1051.437000,...,1483.321060,1480.940466,1484.577288,1488.026571,1491.244494,1495.476524,1503.485237,1515.928956,1524.363787,1530.807130
15,1694.608088,1705.064406,1719.965000,1736.846656,1751.438917,1766.300220,1776.236134,1782.556250,1777.532284,1769.666622,...,2235.685021,2225.980519,2216.271071,2214.711161,2219.986601,2229.354083,2241.734319,2255.814335,2271.278796,2282.386710
16,1334.784983,1339.717721,1356.392486,1365.379557,1377.265302,1378.036488,1380.688372,1380.255405,1378.180402,1376.049717,...,1669.268350,1667.308667,1671.458729,1674.154780,1684.479978,1690.709581,1701.702511,1710.778556,1719.065209,1725.474055
17,2019.777959,2027.259732,2033.126319,2043.181780,2056.546941,2069.015952,2080.837211,2088.141541,2089.310436,2088.328141,...,2955.301825,2941.943913,2935.285107,2938.080812,2952.242743,2964.191045,2974.306713,2986.030808,2999.452452,3007.756522
18,1281.209661,1282.922454,1291.965035,1301.419143,1310.631924,1317.550072,1321.392142,1326.105411,1327.491476,1328.905897,...,2006.713277,1998.988980,1995.636987,1993.080214,1997.334477,2001.533375,2008.207675,2010.549223,2012.195778,2013.209025
19,1524.334953,1533.033595,1544.075170,1554.950791,1567.780304,1577.407838,1582.940237,1581.111415,1575.924584,1572.795395,...,1909.325890,1892.217361,1876.680091,1874.611053,1879.395834,1890.006573,1900.449044,1912.774841,1924.258284,1930.109283
22,1356.215508,1360.137846,1369.393049,1379.548348,1389.074722,1396.943189,1400.688499,1403.704021,1406.454366,1406.942808,...,1933.441015,1924.279521,1918.780563,1922.072009,1926.318398,1933.933973,1944.897805,1953.384245,1960.975898,1959.414635

#### Reshape the Data
The data is often provided in a wide format, so I will unpivot it from wide to long format.

In [37]:
id_col = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

date_columns = [
    col for col in zori.columns
    if col not in id_col
]

zori = zori.melt(
    id_vars = id_col,
    value_vars = date_columns,
    var_name = "Date",
    value_name = "ZORI"
)

# Drop unused columns
zori = zori.drop(columns=["SizeRank", "RegionType"], axis=1)

#### Convert Dates

In [38]:
zori["Date"] = pd.to_datetime(
    zori["Date"],
    errors="coerce"
)

#### Sort the data

In [39]:
zori = zori.sort_values(
    by = ["RegionName", "Date"]).reset_index(drop=True)

zori.head()

   RegionID   RegionName StateName       Date         ZORI
0    394347  Atlanta, GA        GA 2019-01-31  1262.421129
1    394347  Atlanta, GA        GA 2019-02-28  1269.533329
2    394347  Atlanta, GA        GA 2019-03-31  1281.461408
3    394347  Atlanta, GA        GA 2019-04-30  1292.579433
4    394347  Atlanta, GA        GA 2019-05-31  1303.611816

### Housing Inventory Data

In [40]:
# Make a copy so that don't alter the original data
inve = inve_19.copy()

In [41]:
# See the data types in the dataframe
inve.dtypes

RegionID        int64
SizeRank        int64
RegionName     object
RegionType     object
StateName      object
               ...
2026-03-31    float64
2026-04-30    float64
2026-05-31    float64
2026-06-30    float64
2026-07-31    float64
Length: 96, dtype: object

In [42]:
# Date columns shouldn't be float type, so I'll convert them to datetime format later.
inve.select_dtypes(include='float')

,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,...,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31
1,76678.0,74497.0,78192.0,84211.0,91255.0,95966.0,97260.0,95383.0,93359.0,91309.0,...,46780.0,45625.0,41934.0,38091.0,35727.0,37165.0,40652.0,45324.0,48690.0,49835.0
2,26635.0,25849.0,27132.0,28454.0,30124.0,30980.0,31524.0,31208.0,30618.0,29591.0,...,25800.0,24235.0,21849.0,20064.0,19707.0,21155.0,22774.0,24372.0,25314.0,25970.0
3,38250.0,36754.0,39387.0,43789.0,48113.0,50794.0,51883.0,52135.0,51829.0,50805.0,...,23989.0,22985.0,20628.0,18354.0,17282.0,18268.0,19753.0,21673.0,23157.0,24116.0
4,27727.0,27057.0,28543.0,30513.0,32932.0,34785.0,36078.0,36285.0,35472.0,34244.0,...,37328.0,35783.0,33498.0,31315.0,30189.0,31276.0,32753.0,34593.0,35802.0,36826.0
5,27451.0,27492.0,29072.0,30727.0,32388.0,33538.0,34320.0,34363.0,33488.0,32299.0,...,36740.0,35645.0,34098.0,32690.0,32196.0,33445.0,35048.0,36677.0,37657.0,38487.0
6,17421.0,15899.0,16978.0,19236.0,21772.0,22998.0,22900.0,21973.0,21266.0,20799.0,...,17632.0,17100.0,15374.0,13376.0,12350.0,13277.0,15199.0,17433.0,18795.0,19329.0
7,23875.0,22874.0,23683.0,25202.0,26821.0,27540.0,27224.0,26425.0,25524.0,24836.0,...,15798.0,15506.0,14184.0,12711.0,11746.0,12348.0,13554.0,15298.0,16425.0,16933.0
8,52285.0,54550.0,57816.0,59250.0,59411.0,58221.0,56816.0,55223.0,54008.0,53680.0,...,54283.0,53787.0,53115.0,53101.0,53395.0,54312.0,53812.0,52638.0,51044.0,49555.0
9,26971.0,27807.0,29434.0,31132.0,32199.0,33447.0,34126.0,34139.0,33843.0,33465.0,...,33182.0,32072.0,30384.0,28684.0,27810.0,28732.0,30336.0,32227.0,33425.0,33913.0
10,11777.0,10617.0,11316.0,12764.0,14996.0,16577.0,16936.0,16108.0,15702.0,15721.0,...,11228.0,10931.0,9276.0,7561.0,6526.0,7151.0,8755.0,10983.0,12658.0,13013.0
11,25420.0,25252.0,26898.0,27686.0,27934.0,26903.0,25109.0,23293.0,21994.0,21719.0,...,23390.0,23615.0,23016.0,22941.0,23588.0,25540.0,26377.0,26591.0,25798.0,24725.0
12,6431.0,6035.0,6808.0,7824.0,8809.0,9291.0,9376.0,8984.0,8959.0,8992.0,...,9197.0,8547.0,7020.0,5722.0,5506.0,6426.0,7531.0,8431.0,8724.0,8536.0
13,20678.0,20301.0,20873.0,21241.0,21648.0,21580.0,21358.0,21136.0,20820.0,20529.0,...,17223.0,16652.0,15807.0,15080.0,14866.0,15416.0,16005.0,16667.0,16900.0,16880.0
14,16986.0,15770.0,15743.0,16255.0,17733.0,19482.0,20989.0,22033.0,22327.0,22236.0,...,15157.0,14863.0,13841.0,12575.0,11573.0,11652.0,12217.0,13356.0,14371.0,15286.0
15,9544.0,8300.0,8772.0,9585.0,11590.0,13026.0,13915.0,13639.0,12970.0,12071.0,...,12082.0,11143.0,9312.0,7861.0,7481.0,8526.0,10045.0,11842.0,13338.0,14438.0
16,10837.0,9738.0,10117.0,11373.0,13450.0,15353.0,16434.0,16664.0,16468.0,16176.0,...,11710.0,11142.0,9771.0,8299.0,7738.0,8477.0,9927.0,11584.0,12838.0,13612.0
17,9193.0,8908.0,9279.0,9594.0,10061.0,10356.0,10566.0,10535.0,10245.0,9841.0,...,8136.0,7529.0,6741.0,6150.0,6030.0,6501.0,7040.0,7609.0,7908.0,8070.0
18,18975.0,19412.0,20345.0,20254.0,19985.0,19411.0,18914.0,18316.0,17867.0,18342.0,...,23000.0,22515.0,21787.0,21454.0,21495.0,22274.0,22561.0,22678.0,22488.0,22251.0
19,9739.0,9249.0,9945.0,10894.0,12422.0,13742.0,14466.0,14518.0,14218.0,13802.0,...,15549.0,14528.0,12685.0,11104.0,10589.0,11552.0,12880.0,14167.0,15091.0,15652.0
22,12721.0,12876.0,13464.0,13648.0,13752.0,13698.0,13558.0,13215.0,12889.0,13319.0,...,16715.0,16346.0,15777.0,15409.0,15317.0,15813.0,16145.0,16465.0,16567.0,16617.0

#### Reshape the Data
The data is often provided in a wide format, so I will unpivot it from wide to long format.

In [43]:
id_col = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]

date_columns = [
    col for col in inve.columns
    if col not in id_col
]

inve = inve.melt(
    id_vars = id_col,
    value_vars = date_columns,
    var_name = "Date",
    value_name = "Inventory"
)

# Drop unused columns
inve = inve.drop(columns=["SizeRank", "RegionType"], axis=1)

#### Convert Dates

In [44]:
inve["Date"] = pd.to_datetime(
    inve["Date"],
    errors="coerce"
)

#### Sort the data

In [45]:
inve = inve.sort_values(
    by = ["RegionName", "Date"]).reset_index(drop=True)

inve.head()

   RegionID   RegionName StateName       Date  Inventory
0    394347  Atlanta, GA        GA 2019-01-31    26971.0
1    394347  Atlanta, GA        GA 2019-02-28    27807.0
2    394347  Atlanta, GA        GA 2019-03-31    29434.0
3    394347  Atlanta, GA        GA 2019-04-30    31132.0
4    394347  Atlanta, GA        GA 2019-05-31    32199.0

### Merge the ZHVI/ ZORI/ Invetory dataframe into One Datasets

In [66]:
housing1 = zhvi.merge(
    zori,
    on=["RegionName", "StateName", "Date"],
    how="inner"
).drop(columns=["RegionID_y"])

In [67]:
housing1.head()

   RegionID_x   RegionName StateName       Date           ZHVI         ZORI
0      394347  Atlanta, GA        GA 2019-01-31  242626.432983  1262.421129
1      394347  Atlanta, GA        GA 2019-02-28  244173.451945  1269.533329
2      394347  Atlanta, GA        GA 2019-03-31  245478.540927  1281.461408
3      394347  Atlanta, GA        GA 2019-04-30  246510.090887  1292.579433
4      394347  Atlanta, GA        GA 2019-05-31  247317.348859  1303.611816

In [70]:
housing = housing1.merge(
    inve,
    on=["RegionName", "StateName", "Date"],
    how="inner"
).drop(columns=["RegionID"])

housing.rename(columns={"RegionID_x": "RegionID"}, inplace=True)

In [71]:
housing.head()

,RegionID,RegionName,StateName,Date,ZHVI,ZORI,Inventory
0,394347,"Atlanta, GA",GA,2019-01-31,242626.432983,1262.421129,26971.0
1,394347,"Atlanta, GA",GA,2019-02-28,244173.451945,1269.533329,27807.0
2,394347,"Atlanta, GA",GA,2019-03-31,245478.540927,1281.461408,29434.0
3,394347,"Atlanta, GA",GA,2019-04-30,246510.090887,1292.579433,31132.0
4,394347,"Atlanta, GA",GA,2019-05-31,247317.348859,1303.611816,32199.0

#### List of counties in California

#### Reference

1. Metropolitan statistical area: https://en.wikipedia.org/wiki/Metropolitan_statistical_area

2. Zillow Housing: https://www.zillow.com/research/data/